---
title: "DataViz resource library"
subtitle: "from the BIOS² Data Visualization Training"
author: "Prepared by Alex Arkilanian & Katherine Hébert"
date: "September 21-22, 2020"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: 
      collapsed: false
      smooth_scroll: false
    number_sections: true
    theme: "lumen"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Welcome!<br> 

This is an annotated library of data visualization resources we used to build the BIOS² Data Visualization Training, as well as some bonus resources we didn’t have the time to include. Feel free to save this page as a reference for your data visualization adventures!

***

# Books & articles

[Fundamentals of Data Visualization](https://serialmentor.com/dataviz/)<br>
A primer on making informative and compelling figures. This is the website for the book “Fundamentals of Data Visualization” by Claus O. Wilke, published by O’Reilly Media, Inc.

[Data Visualization: A practical introduction](https://socviz.co/index.html#preface)<br>
An accessible primer on how to create effective graphics from data using R (mainly ggplot). This book provides a hands-on introduction to the principles and practice of data visualization, explaining what makes some graphs succeed while others fail, how to make high-quality figures from data using powerful and reproducible methods, and how to think about data visualization in an honest and effective way.

[Data Science Design (Chapter 6: Visualizing Data)](https://link.springer.com/content/pdf/10.1007%2F978-3-319-55444-0.pdf)<br>
Covers the principles that make standard plot designs work, show how they can be misleading if not properly used, and develop a sense of when graphs might be lying, and how to construct better ones.

[From Static to Interactive: Transforming Data Visualization to Improve Transparency](https://doi.org/10.1371/journal.pbio.1002484)<br>
Weissgerber TL, Garovic VD, Savic M, Winham SJ, Milic NM (2016) designed an interactive line graph that demonstrates how dynamic alternatives to static graphics for small sample size studies allow for additional exploration of empirical datasets. This [simple, free, web-based tool](http://statistika.mfub.bg.ac.rs/interactive-graph/) demonstrates the overall concept and may promote widespread use of interactive graphics.

[Data visualization: ambiguity as a fellow traveler](https://doi.org/10.1038/nmeth.2530)<br>
Research that is being done about how to visualize uncertainty in data visualizations.
Marx, V. Nat Methods 10, 613–615 (2013). [https://doi.org/10.1038/nmeth.2530](https://doi.org/10.1038/nmeth.2530)



***

# Design principles

[Gestalt Principles for Data Visualization: Similarity, Proximity & Enclosure](http://emeeks.github.io/gestaltdataviz/section1.html)<br>
Short visual guide to the Gestalt Principles.

[Why scientists need to be better at data visualization](https://www.knowablemagazine.org/article/mind/2019/science-data-visualization?utm_campaign=2019-11-17)<br>
A great overview of principles that could improve how we visualize scientific data and results.

[A collection of graphic pitfalls](https://www.data-to-viz.com/caveats.html)<br>
A collection of short articles about common issues with data visualizations that can mislead or obscure your message.

***

# Choosing a visualization

[Data Viz Project](https://datavizproject.com/)<br> 
This is a great place to get inspiration and guidance about how to choose an appropriate visualization. There are many visualizations we are not used to seeing in ecology!

[From data to Viz | Find the graphic you need](https://www.data-to-viz.com/)<br>
Interactive tool to choose an appropriate visualization type for your data.

***

# Colour

[What to consider when choosing colors for data visualization](https://blog.datawrapper.de/colors/)<br>
A short, visual guide on things to keep in mind when using colour, such as when and how to use colour gradients, the colour grey, etc.

[ColorBrewer: Color Advice for Maps](https://colorbrewer2.org/)<br>
Tool to generate colour palettes for visualizations with colorblind-friendly options. You can also use these palettes in R using the [RColorBrewer](https://cran.r-project.org/web/packages/RColorBrewer/index.html) package, and the `scale_*_brewer()` (for discrete palettes) or `scale_*_distiller()` (for continuous palettes) functions in ggplot2.

[Color.review - Colors that look and work great for everyone](https://color.review/)<br>
Tool to pick or verify colour palettes with high relative contrast between colours, to ensure your information is readable for everyone.

[Coblis — Color Blindness Simulator](https://www.color-blindness.com/coblis-color-blindness-simulator/)<br>
Tool to upload an image and view it as they would appear to a colorblind person, with the option to simulate several color-vision deficiencies.

[500+ Named Colours with rgb and hex values](http://cloford.com/resources/colours/500col.htm)<br>
List of named colours along with their hex values.

[CartoDB/CartoColor](https://github.com/CartoDB/cartocolor)<br>
CARTOColors are a set of custom color palettes built on top of well-known standards for color use on maps, with next generation enhancements for the web and CARTO basemaps. Choose from a selection of sequential, diverging, or qualitative schemes for your next CARTO powered visualization using their [online module](https://carto.com/carto-colors/).

***

# Tools

## R

[The R Graph Gallery](https://www.r-graph-gallery.com/index.html)<br>
A collection of charts made with the R programming language. Hundreds of charts are displayed in several sections, always with their reproducible code available. The gallery makes a focus on the tidyverse and ggplot2.

### Base R

[Cheatsheet: Margins in base R](https://www.r-graph-gallery.com/74-margin-and-oma-cheatsheet)<br>
Edit your margins in base R to accommodate axis titles, legends, captions, etc.!

[Customizing tick marks in base R](https://insileco.github.io/2020/08/29/custom-tick-marks-with-rs-base-graphics-system/)<br>
Seems like a simple thing, but it can be so frustrating! This is a great post about customizing tick marks with base plot in R.

[Animations in R (for time series)](https://insileco.github.io/2017/07/05/animations-in-r-time-series-of-erythemal-irradiance-in-the-st.-lawrence/)<br>
If you want to use animations but don't want to use ggplot2, this demo might help you!

### ggplot2

[Cheatsheet: ggplot2](http://r-statistics.co/ggplot2-cheatsheet.html)<br>
Cheatsheet for ggplot2 in R - anything you want to do is probably covered here!

[Coding Club tutorial: Data Viz Part 1 - Beautiful and informative data visualization](https://ourcodingclub.github.io/tutorials/datavis/)<br>
Great tutorial demonstrating how to customize titles, subtitles, captions, labels, colour palettes, and themes in ggplot2.

[Coding Club tutorial: Data Viz Part 2 - Customizing your figures](https://ourcodingclub.github.io/tutorials/data-vis-2/)<br>
Great tutorial demonstrating how to customize titles, subtitles, captions, labels, colour palettes, and themes in ggplot2.

[ggplot flipbook](https://evamaerey.github.io/ggplot_flipbook/ggplot_flipbook_xaringan.html#1)<br>
A flipbook-style demonstration that builds and customizes plots line by line using ggplot in R.

[gganimate: A Grammar of Animated Graphics](https://github.com/thomasp85/gganimate)<br>
Package to create animated graphics in R (with ggplot2).


## Python

[The Python Graph Gallery](https://python-graph-gallery.com/)<br>
This website displays hundreds of charts, always providing the reproducible python code.

[The Art of Effective Visualization of Multi-dimensional Data](https://towardsdatascience.com/the-art-of-effective-visualization-of-multi-dimensional-data-6c7202990c57)<br>
Covers both univariate (one-dimension) and multivariate (multi-dimensional) data visualization strategies using the Python machine learning ecosystem. 

## Julia

[Julia Plots Gallery](https://goropikari.github.io/PlotsGallery.jl/)<br>
Display of various plots with reproducible code in Julia.

[Plots in Julia](http://docs.juliaplots.org/latest/)<br>
Documentation for the Plots package in Julia, including links to tutorials.

***

# Customization

[Chart Studio](https://plotly.com/chart-studio/)<br>
Web editor to create interactive plots with plotly. You can download the image as .html, or static images, without coding the figure yourself.

[PhyloPic](http://phylopic.org/)<br>
Vector images of living organisms. This is great for ecologists who want to add silhouettes of their organisms onto their plots - search anything, and you will likely find it!

[Add icons on your R plot](https://insileco.github.io/2017/05/23/add-icons-on-your-r-plot/)<br>
Add special icons to your plot as a great way to customize it, and save space with labels!


***

# Inspiration (pretty things!)

[Information is Beautiful](https://informationisbeautiful.net/visualizations/)<br>
Collection of beautiful original visualizations about a variety of topics!

[TidyTuesday](https://github.com/rfordatascience/tidytuesday)
A weekly data project aimed at the R ecosystem, where people wrangle and visualize data in loads of creative ways. Browse what people have created ([#TidyTuesday](https://twitter.com/search?q=%23TidyTuesday) on Twitter is great too!), and the visualizations that have inspired each week's theme.

[Wind currents on Earth](https://earth.nullschool.net/)<br>
Dynamic and interactive map of wind currents on Earth.

[A Day in the Life of Americans](https://flowingdata.com/2015/12/15/a-day-in-the-life-of-americans/)<br>
Dynamic visualisation of how Americans spend their time in an average day.

[2019: The Year in Visual Stories and Graphics](https://www.nytimes.com/interactive/2019/12/30/us/2019-year-in-graphics.html)<br>
Collection of the most popular visualizations by the New York Times in 2019.
